<a href="https://colab.research.google.com/github/JuanLema14/Laboratorios-Modelos-Sistemas-1/blob/main/content/LAB%2001.01%20-%20PRACTICE%20SUBMISSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 01.01 - Practice submission

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [11]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as andres.lema1@udea.edu.co... please wait

-------------
using course session ai4eng.v1.udea.r3::2025.2
success!! you are logged in
-------------


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [3]:

def suma_matrices(a, b):
    result = []
    for i in range(len(a)):
        fila = []
        for j in range(len(a[0])):
            fila.append(a[i][j] + b[i][j])
        result.append(fila)
    return result



comprueba manualmente tu código

In [4]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[8 4]
 [7 3]
 [1 1]]
[[7 5]
 [3 8]
 [3 2]]
[[np.int64(15), np.int64(9)], [np.int64(10), np.int64(11)], [np.int64(4), np.int64(3)]]


#### registra tu solución en línea

In [5]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [6]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([75, 37,  2, 95, 53, 65, 91, 31, 39, 11])

#### tu solución

In [9]:
avg = np.mean(rlist)

#### registra tu solución en línea

In [12]:
student.submit_task(globals(), task_id="task_02");